### ISSUE TITLE
Didn't know how to get in touch with you but just wanted to say thanks

### ISSUE THREAD

**Issue by jayhxmo** [flori4n/isma#1]
This post saved me, thanks so much..! Too low of reputation score to comment, but wanted to somehow say thanks to you for solving problems I was struggling all night.

![image](https://user-images.githubusercontent.com/14072008/81302866-eb6c2680-9048-11ea-8e0b-b79f23b933f6.png)

**Comment by flori4n** [comment]
Wow, thanks you for the effort! I'm glad that helped someone else than me :)
Really appreciate.
Have a nice day !
